// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/character/deploy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deploy a new character with randomized stats to the specified H3 zone. Max 2 alive characters per player.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "character"
                ],
                "summary": "Deploy a character to a zone",
                "parameters": [
                    {
                        "description": "Deploy request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DeployCharacterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.DeployCharacterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns server status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/map/zones": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Compute zone from coordinate, ensure monsters spawned, return all monsters in zone",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "Get map zones",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude",
                        "name": "lng",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ZoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/player/init": {
            "post": {
                "description": "Creates a new player with a session token. No request body needed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "Create a new player",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.InitPlayerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DeployCharacterRequest": {
            "type": "object",
            "required": [
                "h3_zone"
            ],
            "properties": {
                "h3_zone": {
                    "type": "string"
                }
            }
        },
        "handlers.DeployCharacterResponse": {
            "type": "object",
            "properties": {
                "base_damage": {
                    "type": "integer"
                },
                "crit_chance": {
                    "type": "number"
                },
                "crit_multiplier": {
                    "type": "number"
                },
                "damage_amp": {
                    "type": "number"
                },
                "damage_reduction": {
                    "type": "number"
                },
                "h3_index": {
                    "type": "string"
                },
                "h3_zone": {
                    "type": "string"
                },
                "hp": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "max_hp": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.InitPlayerResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "playerId": {
                    "type": "string"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        },
        "handlers.ZoneResponse": {
            "type": "object",
            "properties": {
                "h3_zone": {
                    "type": "string"
                },
                "monsters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.ZoneMonsterResponse"
                    }
                }
            }
        },
        "services.ZoneMonsterResponse": {
            "type": "object",
            "properties": {
                "current_hp": {
                    "type": "integer"
                },
                "h3_index": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_alive": {
                    "type": "boolean"
                },
                "max_hp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "HexSlayer API",
	Description:      "Idle geo-based monster hunting game API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
